<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SECAO_TOPICO', 'doctrine');

/**
 * BaseSECAO_TOPICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seto_cd_chave
 * @property string $seto_nm_descricao
 * @property Doctrine_Collection $TOPICO
 * 
 * @method integer             getSetoCdChave()       Returns the current record's "seto_cd_chave" value
 * @method string              getSetoNmDescricao()   Returns the current record's "seto_nm_descricao" value
 * @method Doctrine_Collection getTOPICO()            Returns the current record's "TOPICO" collection
 * @method SECAO_TOPICO        setSetoCdChave()       Sets the current record's "seto_cd_chave" value
 * @method SECAO_TOPICO        setSetoNmDescricao()   Sets the current record's "seto_nm_descricao" value
 * @method SECAO_TOPICO        setTOPICO()            Sets the current record's "TOPICO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSECAO_TOPICO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SECAO_TOPICO');
        $this->hasColumn('seto_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('seto_nm_descricao', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TOPICO', array(
             'local' => 'seto_cd_chave',
             'foreign' => 'seto_cd_chave'));
    }
}