<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MENSAGEM', 'doctrine');

/**
 * BaseMENSAGEM
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mens_cd_chave
 * @property integer $usua_cd_criador
 * @property integer $topi_cd_chave
 * @property timestamp $mens_dt_criacao
 * @property string $mens_tx_conteudo
 * @property string $mens_nm_anexo
 * @property TOPICO $TOPICO
 * @property USUARIO $USUARIO
 * 
 * @method integer   getMensCdChave()      Returns the current record's "mens_cd_chave" value
 * @method integer   getUsuaCdCriador()    Returns the current record's "usua_cd_criador" value
 * @method integer   getTopiCdChave()      Returns the current record's "topi_cd_chave" value
 * @method timestamp getMensDtCriacao()    Returns the current record's "mens_dt_criacao" value
 * @method string    getMensTxConteudo()   Returns the current record's "mens_tx_conteudo" value
 * @method string    getMensNmAnexo()      Returns the current record's "mens_nm_anexo" value
 * @method TOPICO    getTOPICO()           Returns the current record's "TOPICO" value
 * @method USUARIO   getUSUARIO()          Returns the current record's "USUARIO" value
 * @method MENSAGEM  setMensCdChave()      Sets the current record's "mens_cd_chave" value
 * @method MENSAGEM  setUsuaCdCriador()    Sets the current record's "usua_cd_criador" value
 * @method MENSAGEM  setTopiCdChave()      Sets the current record's "topi_cd_chave" value
 * @method MENSAGEM  setMensDtCriacao()    Sets the current record's "mens_dt_criacao" value
 * @method MENSAGEM  setMensTxConteudo()   Sets the current record's "mens_tx_conteudo" value
 * @method MENSAGEM  setMensNmAnexo()      Sets the current record's "mens_nm_anexo" value
 * @method MENSAGEM  setTOPICO()           Sets the current record's "TOPICO" value
 * @method MENSAGEM  setUSUARIO()          Sets the current record's "USUARIO" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMENSAGEM extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('MENSAGEM');
        $this->hasColumn('mens_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usua_cd_criador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('topi_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mens_dt_criacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('mens_tx_conteudo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('mens_nm_anexo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TOPICO', array(
             'local' => 'topi_cd_chave',
             'foreign' => 'topi_cd_chave'));

        $this->hasOne('USUARIO', array(
             'local' => 'usua_cd_criador',
             'foreign' => 'usua_cd_chave'));
    }
}