<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ARQUIVO', 'doctrine');

/**
 * BaseARQUIVO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $arqu_cd_chave
 * @property integer $tius_cd_chave
 * @property integer $tiar_cd_chave
 * @property integer $seca_cd_chave
 * @property string $arqu_nm_url
 * @property SECAO $SECAO
 * @property TIPO_ARQUIVO $TIPO_ARQUIVO
 * @property TIPO_USUARIO $TIPO_USUARIO
 * 
 * @method integer      getArquCdChave()   Returns the current record's "arqu_cd_chave" value
 * @method integer      getTiusCdChave()   Returns the current record's "tius_cd_chave" value
 * @method integer      getTiarCdChave()   Returns the current record's "tiar_cd_chave" value
 * @method integer      getSecaCdChave()   Returns the current record's "seca_cd_chave" value
 * @method string       getArquNmUrl()     Returns the current record's "arqu_nm_url" value
 * @method SECAO        getSECAO()         Returns the current record's "SECAO" value
 * @method TIPO_ARQUIVO getTIPOARQUIVO()   Returns the current record's "TIPO_ARQUIVO" value
 * @method TIPO_USUARIO getTIPOUSUARIO()   Returns the current record's "TIPO_USUARIO" value
 * @method ARQUIVO      setArquCdChave()   Sets the current record's "arqu_cd_chave" value
 * @method ARQUIVO      setTiusCdChave()   Sets the current record's "tius_cd_chave" value
 * @method ARQUIVO      setTiarCdChave()   Sets the current record's "tiar_cd_chave" value
 * @method ARQUIVO      setSecaCdChave()   Sets the current record's "seca_cd_chave" value
 * @method ARQUIVO      setArquNmUrl()     Sets the current record's "arqu_nm_url" value
 * @method ARQUIVO      setSECAO()         Sets the current record's "SECAO" value
 * @method ARQUIVO      setTIPOARQUIVO()   Sets the current record's "TIPO_ARQUIVO" value
 * @method ARQUIVO      setTIPOUSUARIO()   Sets the current record's "TIPO_USUARIO" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseARQUIVO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ARQUIVO');
        $this->hasColumn('arqu_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tius_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tiar_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('seca_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('arqu_nm_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SECAO', array(
             'local' => 'seca_cd_chave',
             'foreign' => 'seca_cd_chave'));

        $this->hasOne('TIPO_ARQUIVO', array(
             'local' => 'tiar_cd_chave',
             'foreign' => 'tiar_cd_chave'));

        $this->hasOne('TIPO_USUARIO', array(
             'local' => 'tius_cd_chave',
             'foreign' => 'tius_cd_chave'));
    }
}