<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TOPICO', 'doctrine');

/**
 * BaseTOPICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $topi_cd_chave
 * @property integer $usua_cd_criador
 * @property timestamp $topi_dt_criacao
 * @property integer $seto_cd_chave
 * @property string $topi_tx_titulo
 * @property string $topi_tx_conteudo
 * @property string $topi_nm_anexo
 * @property SECAO_TOPICO $SECAO_TOPICO
 * @property USUARIO $USUARIO
 * @property Doctrine_Collection $MENSAGEM
 * 
 * @method integer             getTopiCdChave()      Returns the current record's "topi_cd_chave" value
 * @method integer             getUsuaCdCriador()    Returns the current record's "usua_cd_criador" value
 * @method timestamp           getTopiDtCriacao()    Returns the current record's "topi_dt_criacao" value
 * @method integer             getSetoCdChave()      Returns the current record's "seto_cd_chave" value
 * @method string              getTopiTxTitulo()     Returns the current record's "topi_tx_titulo" value
 * @method string              getTopiTxConteudo()   Returns the current record's "topi_tx_conteudo" value
 * @method string              getTopiNmAnexo()      Returns the current record's "topi_nm_anexo" value
 * @method SECAO_TOPICO        getSECAOTOPICO()      Returns the current record's "SECAO_TOPICO" value
 * @method USUARIO             getUSUARIO()          Returns the current record's "USUARIO" value
 * @method Doctrine_Collection getMENSAGEM()         Returns the current record's "MENSAGEM" collection
 * @method TOPICO              setTopiCdChave()      Sets the current record's "topi_cd_chave" value
 * @method TOPICO              setUsuaCdCriador()    Sets the current record's "usua_cd_criador" value
 * @method TOPICO              setTopiDtCriacao()    Sets the current record's "topi_dt_criacao" value
 * @method TOPICO              setSetoCdChave()      Sets the current record's "seto_cd_chave" value
 * @method TOPICO              setTopiTxTitulo()     Sets the current record's "topi_tx_titulo" value
 * @method TOPICO              setTopiTxConteudo()   Sets the current record's "topi_tx_conteudo" value
 * @method TOPICO              setTopiNmAnexo()      Sets the current record's "topi_nm_anexo" value
 * @method TOPICO              setSECAOTOPICO()      Sets the current record's "SECAO_TOPICO" value
 * @method TOPICO              setUSUARIO()          Sets the current record's "USUARIO" value
 * @method TOPICO              setMENSAGEM()         Sets the current record's "MENSAGEM" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTOPICO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TOPICO');
        $this->hasColumn('topi_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usua_cd_criador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('topi_dt_criacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('seto_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('topi_tx_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('topi_tx_conteudo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('topi_nm_anexo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SECAO_TOPICO', array(
             'local' => 'seto_cd_chave',
             'foreign' => 'seto_cd_chave'));

        $this->hasOne('USUARIO', array(
             'local' => 'usua_cd_criador',
             'foreign' => 'usua_cd_chave'));

        $this->hasMany('MENSAGEM', array(
             'local' => 'topi_cd_chave',
             'foreign' => 'topi_cd_chave'));
    }
}