<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ARTIGO_EVENTO', 'doctrine');

/**
 * BaseARTIGO_EVENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $arev_cd_chave
 * @property integer $inev_cd_chave
 * @property string $arev_nm_url
 * @property INSCRICAO_EVENTO $INSCRICAO_EVENTO
 * 
 * @method integer          getArevCdChave()      Returns the current record's "arev_cd_chave" value
 * @method integer          getInevCdChave()      Returns the current record's "inev_cd_chave" value
 * @method string           getArevNmUrl()        Returns the current record's "arev_nm_url" value
 * @method INSCRICAO_EVENTO getINSCRICAOEVENTO()  Returns the current record's "INSCRICAO_EVENTO" value
 * @method ARTIGO_EVENTO    setArevCdChave()      Sets the current record's "arev_cd_chave" value
 * @method ARTIGO_EVENTO    setInevCdChave()      Sets the current record's "inev_cd_chave" value
 * @method ARTIGO_EVENTO    setArevNmUrl()        Sets the current record's "arev_nm_url" value
 * @method ARTIGO_EVENTO    setINSCRICAOEVENTO()  Sets the current record's "INSCRICAO_EVENTO" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseARTIGO_EVENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ARTIGO_EVENTO');
        $this->hasColumn('arev_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('inev_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('arev_nm_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('INSCRICAO_EVENTO', array(
             'local' => 'inev_cd_chave',
             'foreign' => 'inev_cd_chave'));
    }
}