<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LINK_EXTERNO', 'doctrine');

/**
 * BaseLINK_EXTERNO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $liex_cd_chave
 * @property string $liex_nm_url
 * @property string $liex_nm_rotulo
 * @property string $liex_nm_imagem
 * 
 * @method integer      getLiexCdChave()    Returns the current record's "liex_cd_chave" value
 * @method string       getLiexNmUrl()      Returns the current record's "liex_nm_url" value
 * @method string       getLiexNmRotulo()   Returns the current record's "liex_nm_rotulo" value
 * @method string       getLiexNmImagem()   Returns the current record's "liex_nm_imagem" value
 * @method LINK_EXTERNO setLiexCdChave()    Sets the current record's "liex_cd_chave" value
 * @method LINK_EXTERNO setLiexNmUrl()      Sets the current record's "liex_nm_url" value
 * @method LINK_EXTERNO setLiexNmRotulo()   Sets the current record's "liex_nm_rotulo" value
 * @method LINK_EXTERNO setLiexNmImagem()   Sets the current record's "liex_nm_imagem" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLINK_EXTERNO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LINK_EXTERNO');
        $this->hasColumn('liex_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('liex_nm_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('liex_nm_rotulo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('liex_nm_imagem', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}