<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_ARQUIVO', 'doctrine');

/**
 * BaseTIPO_ARQUIVO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tiar_cd_chave
 * @property string $tiar_nm_descricao
 * @property Doctrine_Collection $ARQUIVO
 * 
 * @method integer             getTiarCdChave()       Returns the current record's "tiar_cd_chave" value
 * @method string              getTiarNmDescricao()   Returns the current record's "tiar_nm_descricao" value
 * @method Doctrine_Collection getARQUIVO()           Returns the current record's "ARQUIVO" collection
 * @method TIPO_ARQUIVO        setTiarCdChave()       Sets the current record's "tiar_cd_chave" value
 * @method TIPO_ARQUIVO        setTiarNmDescricao()   Sets the current record's "tiar_nm_descricao" value
 * @method TIPO_ARQUIVO        setARQUIVO()           Sets the current record's "ARQUIVO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_ARQUIVO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_ARQUIVO');
        $this->hasColumn('tiar_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tiar_nm_descricao', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ARQUIVO', array(
             'local' => 'tiar_cd_chave',
             'foreign' => 'tiar_cd_chave'));
    }
}