<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RELATORIO', 'doctrine');

/**
 * BaseRELATORIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rela_cd_chave
 * @property integer $proj_cd_chave
 * @property string $rela_tx_descricao
 * @property string $rela_nm_documento
 * @property string $rela_nm_autores
 * @property PROJETO $PROJETO
 * 
 * @method integer   getRelaCdChave()       Returns the current record's "rela_cd_chave" value
 * @method integer   getProjCdChave()       Returns the current record's "proj_cd_chave" value
 * @method string    getRelaTxDescricao()   Returns the current record's "rela_tx_descricao" value
 * @method string    getRelaNmDocumento()   Returns the current record's "rela_nm_documento" value
 * @method string    getRelaNmAutores()     Returns the current record's "rela_nm_autores" value
 * @method PROJETO   getPROJETO()           Returns the current record's "PROJETO" value
 * @method RELATORIO setRelaCdChave()       Sets the current record's "rela_cd_chave" value
 * @method RELATORIO setProjCdChave()       Sets the current record's "proj_cd_chave" value
 * @method RELATORIO setRelaTxDescricao()   Sets the current record's "rela_tx_descricao" value
 * @method RELATORIO setRelaNmDocumento()   Sets the current record's "rela_nm_documento" value
 * @method RELATORIO setRelaNmAutores()     Sets the current record's "rela_nm_autores" value
 * @method RELATORIO setPROJETO()           Sets the current record's "PROJETO" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRELATORIO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RELATORIO');
        $this->hasColumn('rela_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('proj_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rela_tx_descricao', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('rela_nm_documento', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('rela_nm_autores', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PROJETO', array(
             'local' => 'proj_cd_chave',
             'foreign' => 'proj_cd_chave'));
    }
}