<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INSCRICAO_EVENTO', 'doctrine');

/**
 * BaseINSCRICAO_EVENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $inev_cd_chave
 * @property integer $usua_cd_chave
 * @property integer $even_cd_chave
 * @property timestamp $inev_dt_confirmacao
 * @property EVENTO $EVENTO
 * @property USUARIO $USUARIO
 * @property Doctrine_Collection $ARTIGO_EVENTO
 * 
 * @method integer             getInevCdChave()         Returns the current record's "inev_cd_chave" value
 * @method integer             getUsuaCdChave()         Returns the current record's "usua_cd_chave" value
 * @method integer             getEvenCdChave()         Returns the current record's "even_cd_chave" value
 * @method timestamp           getInevDtConfirmacao()   Returns the current record's "inev_dt_confirmacao" value
 * @method EVENTO              getEVENTO()              Returns the current record's "EVENTO" value
 * @method USUARIO             getUSUARIO()             Returns the current record's "USUARIO" value
 * @method Doctrine_Collection getARTIGOEVENTO()        Returns the current record's "ARTIGO_EVENTO" collection
 * @method INSCRICAO_EVENTO    setInevCdChave()         Sets the current record's "inev_cd_chave" value
 * @method INSCRICAO_EVENTO    setUsuaCdChave()         Sets the current record's "usua_cd_chave" value
 * @method INSCRICAO_EVENTO    setEvenCdChave()         Sets the current record's "even_cd_chave" value
 * @method INSCRICAO_EVENTO    setInevDtConfirmacao()   Sets the current record's "inev_dt_confirmacao" value
 * @method INSCRICAO_EVENTO    setEVENTO()              Sets the current record's "EVENTO" value
 * @method INSCRICAO_EVENTO    setUSUARIO()             Sets the current record's "USUARIO" value
 * @method INSCRICAO_EVENTO    setARTIGOEVENTO()        Sets the current record's "ARTIGO_EVENTO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINSCRICAO_EVENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INSCRICAO_EVENTO');
        $this->hasColumn('inev_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usua_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('even_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('inev_dt_confirmacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EVENTO', array(
             'local' => 'even_cd_chave',
             'foreign' => 'even_cd_chave'));

        $this->hasOne('USUARIO', array(
             'local' => 'usua_cd_chave',
             'foreign' => 'usua_cd_chave'));

        $this->hasMany('ARTIGO_EVENTO', array(
             'local' => 'inev_cd_chave',
             'foreign' => 'inev_cd_chave'));
    }
}