<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PROJETO', 'doctrine');

/**
 * BasePROJETO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $proj_cd_chave
 * @property integer $stpr_cd_chave
 * @property integer $tius_cd_chave
 * @property string $proj_nm_titulo
 * @property string $proj_tx_descricao
 * @property string $proj_nm_documento
 * @property STATUS_PROJETO $STATUS_PROJETO
 * @property TIPO_USUARIO $TIPO_USUARIO
 * @property Doctrine_Collection $RELATORIO
 * 
 * @method integer             getProjCdChave()       Returns the current record's "proj_cd_chave" value
 * @method integer             getStprCdChave()       Returns the current record's "stpr_cd_chave" value
 * @method integer             getTiusCdChave()       Returns the current record's "tius_cd_chave" value
 * @method string              getProjNmTitulo()      Returns the current record's "proj_nm_titulo" value
 * @method string              getProjTxDescricao()   Returns the current record's "proj_tx_descricao" value
 * @method string              getProjNmDocumento()   Returns the current record's "proj_nm_documento" value
 * @method STATUS_PROJETO      getSTATUSPROJETO()     Returns the current record's "STATUS_PROJETO" value
 * @method TIPO_USUARIO        getTIPOUSUARIO()       Returns the current record's "TIPO_USUARIO" value
 * @method Doctrine_Collection getRELATORIO()         Returns the current record's "RELATORIO" collection
 * @method PROJETO             setProjCdChave()       Sets the current record's "proj_cd_chave" value
 * @method PROJETO             setStprCdChave()       Sets the current record's "stpr_cd_chave" value
 * @method PROJETO             setTiusCdChave()       Sets the current record's "tius_cd_chave" value
 * @method PROJETO             setProjNmTitulo()      Sets the current record's "proj_nm_titulo" value
 * @method PROJETO             setProjTxDescricao()   Sets the current record's "proj_tx_descricao" value
 * @method PROJETO             setProjNmDocumento()   Sets the current record's "proj_nm_documento" value
 * @method PROJETO             setSTATUSPROJETO()     Sets the current record's "STATUS_PROJETO" value
 * @method PROJETO             setTIPOUSUARIO()       Sets the current record's "TIPO_USUARIO" value
 * @method PROJETO             setRELATORIO()         Sets the current record's "RELATORIO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePROJETO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PROJETO');
        $this->hasColumn('proj_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('stpr_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tius_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('proj_nm_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('proj_tx_descricao', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('proj_nm_documento', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('STATUS_PROJETO', array(
             'local' => 'stpr_cd_chave',
             'foreign' => 'stpr_cd_chave'));

        $this->hasOne('TIPO_USUARIO', array(
             'local' => 'tius_cd_chave',
             'foreign' => 'tius_cd_chave'));

        $this->hasMany('RELATORIO', array(
             'local' => 'proj_cd_chave',
             'foreign' => 'proj_cd_chave'));
    }
}