<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AJUDA', 'doctrine');

/**
 * BaseAJUDA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ajud_cd_chave
 * @property string $ajud_nm_assunto
 * @property string $ajud_nm_pergunta
 * @property string $ajud_tx_resposta
 * @property timestamp $ajud_dt_inclusao
 * @property string $ajud_nm_autor
 * 
 * @method integer   getAjudCdChave()      Returns the current record's "ajud_cd_chave" value
 * @method string    getAjudNmAssunto()    Returns the current record's "ajud_nm_assunto" value
 * @method string    getAjudNmPergunta()   Returns the current record's "ajud_nm_pergunta" value
 * @method string    getAjudTxResposta()   Returns the current record's "ajud_tx_resposta" value
 * @method timestamp getAjudDtInclusao()   Returns the current record's "ajud_dt_inclusao" value
 * @method string    getAjudNmAutor()      Returns the current record's "ajud_nm_autor" value
 * @method AJUDA     setAjudCdChave()      Sets the current record's "ajud_cd_chave" value
 * @method AJUDA     setAjudNmAssunto()    Sets the current record's "ajud_nm_assunto" value
 * @method AJUDA     setAjudNmPergunta()   Sets the current record's "ajud_nm_pergunta" value
 * @method AJUDA     setAjudTxResposta()   Sets the current record's "ajud_tx_resposta" value
 * @method AJUDA     setAjudDtInclusao()   Sets the current record's "ajud_dt_inclusao" value
 * @method AJUDA     setAjudNmAutor()      Sets the current record's "ajud_nm_autor" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAJUDA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('AJUDA');
        $this->hasColumn('ajud_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ajud_nm_assunto', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('ajud_nm_pergunta', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('ajud_tx_resposta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ajud_dt_inclusao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ajud_nm_autor', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}