<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EVENTO', 'doctrine');

/**
 * BaseEVENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $even_cd_chave
 * @property timestamp $even_dt_realizacao
 * @property string $even_nm_local
 * @property string $even_nm_organizacao
 * @property string $even_nm_hotsite
 * @property Doctrine_Collection $INSCRICAO_EVENTO
 * @property Doctrine_Collection $MATERIAL_EVENTO
 * 
 * @method integer             getEvenCdChave()         Returns the current record's "even_cd_chave" value
 * @method timestamp           getEvenDtRealizacao()    Returns the current record's "even_dt_realizacao" value
 * @method string              getEvenNmLocal()         Returns the current record's "even_nm_local" value
 * @method string              getEvenNmOrganizacao()   Returns the current record's "even_nm_organizacao" value
 * @method string              getEvenNmHotsite()       Returns the current record's "even_nm_hotsite" value
 * @method Doctrine_Collection getINSCRICAOEVENTO()     Returns the current record's "INSCRICAO_EVENTO" collection
 * @method Doctrine_Collection getMATERIALEVENTO()      Returns the current record's "MATERIAL_EVENTO" collection
 * @method EVENTO              setEvenCdChave()         Sets the current record's "even_cd_chave" value
 * @method EVENTO              setEvenDtRealizacao()    Sets the current record's "even_dt_realizacao" value
 * @method EVENTO              setEvenNmLocal()         Sets the current record's "even_nm_local" value
 * @method EVENTO              setEvenNmOrganizacao()   Sets the current record's "even_nm_organizacao" value
 * @method EVENTO              setEvenNmHotsite()       Sets the current record's "even_nm_hotsite" value
 * @method EVENTO              setINSCRICAOEVENTO()     Sets the current record's "INSCRICAO_EVENTO" collection
 * @method EVENTO              setMATERIALEVENTO()      Sets the current record's "MATERIAL_EVENTO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEVENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('EVENTO');
        $this->hasColumn('even_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('even_dt_realizacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('even_nm_local', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('even_nm_organizacao', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('even_nm_hotsite', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('INSCRICAO_EVENTO', array(
             'local' => 'even_cd_chave',
             'foreign' => 'even_cd_chave'));

        $this->hasMany('MATERIAL_EVENTO', array(
             'local' => 'even_cd_chave',
             'foreign' => 'even_cd_chave'));
    }
}