<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MATERIAL_EVENTO', 'doctrine');

/**
 * BaseMATERIAL_EVENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $maev_cd_chave
 * @property integer $even_cd_chave
 * @property string $maev_nm_url
 * @property EVENTO $EVENTO
 * 
 * @method integer         getMaevCdChave()   Returns the current record's "maev_cd_chave" value
 * @method integer         getEvenCdChave()   Returns the current record's "even_cd_chave" value
 * @method string          getMaevNmUrl()     Returns the current record's "maev_nm_url" value
 * @method EVENTO          getEVENTO()        Returns the current record's "EVENTO" value
 * @method MATERIAL_EVENTO setMaevCdChave()   Sets the current record's "maev_cd_chave" value
 * @method MATERIAL_EVENTO setEvenCdChave()   Sets the current record's "even_cd_chave" value
 * @method MATERIAL_EVENTO setMaevNmUrl()     Sets the current record's "maev_nm_url" value
 * @method MATERIAL_EVENTO setEVENTO()        Sets the current record's "EVENTO" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMATERIAL_EVENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('MATERIAL_EVENTO');
        $this->hasColumn('maev_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('even_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('maev_nm_url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EVENTO', array(
             'local' => 'even_cd_chave',
             'foreign' => 'even_cd_chave'));
    }
}