<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_NOTICIA', 'doctrine');

/**
 * BaseTIPO_NOTICIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tino_cd_chave
 * @property string $tino_nm_descricao
 * @property Doctrine_Collection $NOTICIA
 * 
 * @method integer             getTinoCdChave()       Returns the current record's "tino_cd_chave" value
 * @method string              getTinoNmDescricao()   Returns the current record's "tino_nm_descricao" value
 * @method Doctrine_Collection getNOTICIA()           Returns the current record's "NOTICIA" collection
 * @method TIPO_NOTICIA        setTinoCdChave()       Sets the current record's "tino_cd_chave" value
 * @method TIPO_NOTICIA        setTinoNmDescricao()   Sets the current record's "tino_nm_descricao" value
 * @method TIPO_NOTICIA        setNOTICIA()           Sets the current record's "NOTICIA" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_NOTICIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_NOTICIA');
        $this->hasColumn('tino_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tino_nm_descricao', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NOTICIA', array(
             'local' => 'tino_cd_chave',
             'foreign' => 'tino_cd_chave'));
    }
}