<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NOTICIA', 'doctrine');

/**
 * BaseNOTICIA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $noti_cd_chave
 * @property integer $tino_cd_chave
 * @property string $noti_nm_titulo
 * @property string $noti_tx_conteudo
 * @property string $noti_nm_fonte
 * @property timestamp $noti_dt_publicacao
 * @property string $noti_nm_link
 * @property TIPO_NOTICIA $TIPO_NOTICIA
 * 
 * @method integer      getNotiCdChave()        Returns the current record's "noti_cd_chave" value
 * @method integer      getTinoCdChave()        Returns the current record's "tino_cd_chave" value
 * @method string       getNotiNmTitulo()       Returns the current record's "noti_nm_titulo" value
 * @method string       getNotiTxConteudo()     Returns the current record's "noti_tx_conteudo" value
 * @method string       getNotiNmFonte()        Returns the current record's "noti_nm_fonte" value
 * @method timestamp    getNotiDtPublicacao()   Returns the current record's "noti_dt_publicacao" value
 * @method string       getNotiNmLink()         Returns the current record's "noti_nm_link" value
 * @method TIPO_NOTICIA getTIPONOTICIA()        Returns the current record's "TIPO_NOTICIA" value
 * @method NOTICIA      setNotiCdChave()        Sets the current record's "noti_cd_chave" value
 * @method NOTICIA      setTinoCdChave()        Sets the current record's "tino_cd_chave" value
 * @method NOTICIA      setNotiNmTitulo()       Sets the current record's "noti_nm_titulo" value
 * @method NOTICIA      setNotiTxConteudo()     Sets the current record's "noti_tx_conteudo" value
 * @method NOTICIA      setNotiNmFonte()        Sets the current record's "noti_nm_fonte" value
 * @method NOTICIA      setNotiDtPublicacao()   Sets the current record's "noti_dt_publicacao" value
 * @method NOTICIA      setNotiNmLink()         Sets the current record's "noti_nm_link" value
 * @method NOTICIA      setTIPONOTICIA()        Sets the current record's "TIPO_NOTICIA" value
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNOTICIA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('NOTICIA');
        $this->hasColumn('noti_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tino_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('noti_nm_titulo', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('noti_tx_conteudo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('noti_nm_fonte', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('noti_dt_publicacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('noti_nm_link', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TIPO_NOTICIA', array(
             'local' => 'tino_cd_chave',
             'foreign' => 'tino_cd_chave'));
    }
}