<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('USUARIO', 'doctrine');

/**
 * BaseUSUARIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usua_cd_chave
 * @property string $usua_nm_usuario
 * @property string $usua_cd_senha
 * @property integer $tius_cd_chave
 * @property string $usua_nm_nome
 * @property timestamp $usua_dt_nascimento
 * @property TIPO_USUARIO $TIPO_USUARIO
 * @property Doctrine_Collection $INSCRICAO_EVENTO
 * @property Doctrine_Collection $MENSAGEM
 * @property Doctrine_Collection $TOPICO
 * 
 * @method integer             getUsuaCdChave()        Returns the current record's "usua_cd_chave" value
 * @method string              getUsuaNmUsuario()      Returns the current record's "usua_nm_usuario" value
 * @method string              getUsuaCdSenha()        Returns the current record's "usua_cd_senha" value
 * @method integer             getTiusCdChave()        Returns the current record's "tius_cd_chave" value
 * @method string              getUsuaNmNome()         Returns the current record's "usua_nm_nome" value
 * @method timestamp           getUsuaDtNascimento()   Returns the current record's "usua_dt_nascimento" value
 * @method TIPO_USUARIO        getTIPOUSUARIO()        Returns the current record's "TIPO_USUARIO" value
 * @method Doctrine_Collection getINSCRICAOEVENTO()    Returns the current record's "INSCRICAO_EVENTO" collection
 * @method Doctrine_Collection getMENSAGEM()           Returns the current record's "MENSAGEM" collection
 * @method Doctrine_Collection getTOPICO()             Returns the current record's "TOPICO" collection
 * @method USUARIO             setUsuaCdChave()        Sets the current record's "usua_cd_chave" value
 * @method USUARIO             setUsuaNmUsuario()      Sets the current record's "usua_nm_usuario" value
 * @method USUARIO             setUsuaCdSenha()        Sets the current record's "usua_cd_senha" value
 * @method USUARIO             setTiusCdChave()        Sets the current record's "tius_cd_chave" value
 * @method USUARIO             setUsuaNmNome()         Sets the current record's "usua_nm_nome" value
 * @method USUARIO             setUsuaDtNascimento()   Sets the current record's "usua_dt_nascimento" value
 * @method USUARIO             setTIPOUSUARIO()        Sets the current record's "TIPO_USUARIO" value
 * @method USUARIO             setINSCRICAOEVENTO()    Sets the current record's "INSCRICAO_EVENTO" collection
 * @method USUARIO             setMENSAGEM()           Sets the current record's "MENSAGEM" collection
 * @method USUARIO             setTOPICO()             Sets the current record's "TOPICO" collection
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUSUARIO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('USUARIO');
        $this->hasColumn('usua_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usua_nm_usuario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('usua_cd_senha', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('tius_cd_chave', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usua_nm_nome', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('usua_dt_nascimento', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TIPO_USUARIO', array(
             'local' => 'tius_cd_chave',
             'foreign' => 'tius_cd_chave'));

        $this->hasMany('INSCRICAO_EVENTO', array(
             'local' => 'usua_cd_chave',
             'foreign' => 'usua_cd_chave'));

        $this->hasMany('MENSAGEM', array(
             'local' => 'usua_cd_chave',
             'foreign' => 'usua_cd_criador'));

        $this->hasMany('TOPICO', array(
             'local' => 'usua_cd_chave',
             'foreign' => 'usua_cd_criador'));
    }
}