secao_topico:
  class: sfDoctrineRouteCollection
  options:
    model:                SECAO_TOPICO
    module:               TopicSection
    prefix_path:          /TopicSection
    column:               seto_cd_chave
    with_wildcard_routes: true

mensagem:
  class: sfDoctrineRouteCollection
  options:
    model:                Mensagem
    module:               Message
    prefix_path:          /Message
    column:               mens_cd_chave
    with_wildcard_routes: true

noticia_Notice:
  class: sfDoctrineRouteCollection
  options:
    model:                Noticia
    module:               Notice
    prefix_path:          /Notice
    column:               noti_cd_chave
    with_wildcard_routes: true

noticia:
  class: sfDoctrineRouteCollection
  options:
    model:                Noticia
    module:               News
    prefix_path:          /News
    column:               noti_cd_chave
    with_wildcard_routes: true

topico:
  class: sfDoctrineRouteCollection
  options:
    model:                Topico
    module:               Topic
    prefix_path:          /Topic
    column:               topi_cd_chave
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: Home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
