<?php

/**
 * AJUDATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AJUDATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AJUDATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AJUDA');
    }
}