<?php

/**
 * ARQUIVOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ARQUIVOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ARQUIVOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ARQUIVO');
    }
}