<?php

/**
 * ARTIGO_EVENTOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ARTIGO_EVENTOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ARTIGO_EVENTOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ARTIGO_EVENTO');
    }
}