<?php

/**
 * EVENTOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EVENTOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EVENTOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EVENTO');
    }
}