<?php

/**
 * INSCRICAO_EVENTOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class INSCRICAO_EVENTOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object INSCRICAO_EVENTOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('INSCRICAO_EVENTO');
    }
}