<?php

/**
 * LINK_EXTERNOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LINK_EXTERNOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LINK_EXTERNOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LINK_EXTERNO');
    }
}