<?php

/**
 * MATERIAL_EVENTOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MATERIAL_EVENTOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MATERIAL_EVENTOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MATERIAL_EVENTO');
    }
}