<?php

/**
 * MENSAGEMTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MENSAGEMTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MENSAGEMTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MENSAGEM');
    }
}