<?php

/**
 * NOTICIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NOTICIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NOTICIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NOTICIA');
    }
}