<?php

/**
 * PROJETOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PROJETOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PROJETOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PROJETO');
    }
}