<?php

/**
 * RELATORIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RELATORIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RELATORIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RELATORIO');
    }
}