<?php

/**
 * SECAO_TOPICOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SECAO_TOPICOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SECAO_TOPICOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SECAO_TOPICO');
    }
}