<?php

/**
 * SECAOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SECAOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SECAOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SECAO');
    }
}