<?php

/**
 * SECAO_TOPICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Ricino
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SECAO_TOPICO extends BaseSECAO_TOPICO
{
}
