<?php

/**
 * STATUS_PROJETOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class STATUS_PROJETOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object STATUS_PROJETOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('STATUS_PROJETO');
    }
}