<?php

/**
 * TIPO_USUARIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_USUARIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_USUARIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_USUARIO');
    }
}