<?php

/**
 * TIPO_NOTICIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_NOTICIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_NOTICIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_NOTICIA');
    }
}