<?php

/**
 * TIPO_ARQUIVOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_ARQUIVOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_ARQUIVOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_ARQUIVO');
    }
}