<?php

/**
 * USUARIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class USUARIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object USUARIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('USUARIO');
    }
}