<div class="titulo1">
    <h1>Notícias</h1>
    
    <h2 id="news0">Setor naval cria rede de desenvolvimento</h2>
    <p>Indústria, governo e academia se articulam para criar um plano estratégico para o setor naval brasileiro. A idéia é integrar ações e direcionar recursos para pesquisa e desenvolvimento tecnológico dessa indústria. Transpetro, Usiminas, DNV, Estaleiro Atlântico Sul, BNDES, Ministério do Desenvolvimento e entidades como Sinaval, SOBENA e Syndarma estão entre os integrantes da Rede de Inovação para a Competitividade da Indústria Naval e Offshore. A criação da RICINO foi efetivada semana passada, no 23° Congresso da SOBENA, quando foram apresentadas propostas para o Plano Nacional 2011. As ações da RICINO serão divididas em núcleos coordenados por universidades. Os regionais ficarão em Pernambuco e Rio Grande do Sul, onde estão pólos navais de Suape e Rio Grande. Haverá ainda núcleos temáticos: construção naval e offshore, com COPPE/UFRJ, no Rio; embarcações e sistemas offshore, com a USP; e cadeia produtiva, com o IPT. “De início, pretendemos captar R$ 80 milhões para financiar centros de tecnologia e formação, demandas da indústria”, diz Sergio Garcia, coordenador do comitê gestor provisório. A carteira já apresentada propõe a criação do Centro de Tecnologia da Construção Naval e Offshore e do Centro Avançado de Formação de Técnicos em Construção Naval, no Rio; e do Parque Científico-Tecnológico do Mar (Oceantec) e centros avançados em TI e Automação e Formação em Tecnologias de Solda, em Rio Grande (RS). “A questão da mão-de-obra é crítica. A indústria ficou parada nos anos 90. Hoje muitos dos 50 mil trabalhadores estão prestes a se aposentar, ao mesmo tempo em que surgem novos estaleiros no país” diz Garcia.</p>
    <h3>Fonte: Coluna Negócios & Cia do jornal O Globo - Flávia Oliveira - 03/11/2010. </h3>
    <br />

    <h2 id="news1">RICINO no SOBENA 2010</h2>
    <p>Um dos destaques do 23° Congresso Nacional de Transporte Aquaviário, Construção Naval e Offshore - SOBENA 2010, que aconteceu no período de 25 a 29 de outubro de 2010, foi a instalação da Rede de Inovação para a Competitividade da Indústria Naval e Offshore (RICINO).  A rede tem como objetivo integrar ações e direcionar recursos para pesquisa e desenvolvimento tecnológico dessa indústria. A RICINO reúne empresas, universidades e entidades ligadas ao setor.  “Essa articulação entre academia, empresas e governo será de grande importância para o desenvolvimento do setor naval”, comentou Sergio Garcia, coordenador do comitê gestor da Rede e diretor administrativo da SOBENA.  As ações da RICINO foram divididas em núcleos coordenados por universidades. Os regionais serão em Pernambuco e Rio Grande do Sul. Segundo Sergio Garcia numa etapa inicial a Rede pretende captar R$ 80 milhões para financiar centros de tecnologia e formação, que são demandas da indústria.  Está prevista ainda a criação de um Centro de Tecnologia da Construção Naval e Offshore e do Centro Avançado de Formação de Técnicos em Construção Naval, ambos no Rio de Janeiro. Já em Rio Grande, onde a demanda também está aquecida devido às recentes encomendas de plataformas, está prevista a implantação do Parque Científico-Tecnológico do Mar (Oceantec) e centros avançados em TI e automação e formação em tecnologias de solda.</p>
    <h3>Fonte: Portos e Navios - Data: 01/12/2010</h3>
    <br />
    
    <h2 id="news2">Com a retomada de negócios graças a investimentos no mercado de óleo e gás, a indústria naval brasileira aposta em pesquisa e desenvolvimento</h2>
    <br />
    <p>Com a retomada de negócios graças a investimentos no mercado de óleo e gás, a indústria naval brasileira aposta em pesquisa e desenvolvimento. O setor lançou no ano passado a Rede de Inovação para Competitividade da Indústria Naval e Offshore (RICINO), que pretende criar, nos próximos quatro anos, um centro de tecnologia e uma unidade de formação de técnicos em construção naval no Rio de Janeiro (RJ).
    <p>"O objetivo é articular ações de P&D na indústria e em instituições da área", diz Floriano Pires, vice-coordenador do comitê gestor da rede, que articula um parque científico do mar e centros avançados de tecnologias de solda no Rio Grande do Sul. "Por meio de agências de fomento, órgãos do governo e empresas, estamos trabalhando para viabilizar projetos avaliados em R$ 60 milhões", afirma.</p>
    <p>Segundo Pires, que é professor de engenharia oceânica da COPPE/UFRJ e vice-presidente da Sociedade Brasileira de Engenharia Naval (SOBENA), a rede pretende trabalhar com as demandas da indústria e disseminar informações tecnológicas: um portal na internet, financiado pelo Ministério do Desenvolvimento, Indústria e Comércio Exterior (MDIC), deve estar pronto nos próximos dois meses.</p>
    <p>As iniciativas chegam em boa hora. De acordo com o Sindicato Nacional da Indústria da Construção e Reparação Naval e Offshore (Sinaval), o setor emprega mais de 80 mil pessoas. Com a expansão do número de estaleiros e encomendas, outros 15 mil empregos devem ser gerados nos próximos três anos - e a capacitação de pessoal será decisiva para acompanhar o ritmo dos negócios.</p>
    <p>A indústria naval é considerada prioridade para o governo federal. Não só pela rapidez de gerar trabalho e renda, mas pela chegada de investidores robustos atraídos pelo pré-sal. Por conta disso, a demanda por embarcações de transporte de óleo e gás, graneleiros, sondas e plataformas de petróleo promete gerar um crescimento garantido ao setor. "Precisamos alcançar padrões de produtividade competitivos em curto prazo e, para isso, é necessário um forte investimento em P&D e inovação."</p>
    <p>Além da SOBENA e do Sinaval, as instituições integrantes da RICINO são o Sindicato das Empresas de Navegação Marítima (Syndarma) e o Centro de Excelência em Engenharia Naval e Oceânica (Ceeno), formado pela COPPE, Instituto de Pesquisas Tecnológicas (IPT), Universidade de São Paulo (USP), TRANSPETRO e CENPES, o centro de pesquisas da PETROBRAS.</p>
    <p>As ações da rede são divididas em cinco núcleos: projetos de embarcações, cadeia produtiva e tecnologia da construção, além dos regionais Nordeste-Norte, em Pernambuco, e Sul, no Rio Grande do Sul, Estados que abrigam os polos navais de Suape e da cidade de Rio Grande, respectivamente. "As unidades promovem a articulação e a elaboração de projetos em suas respectivas áreas", diz Pires. Empresas como a Usiminas e o Estaleiro Atlântico Sul também fazem parte dos núcleos.</p>
    <h3>Fonte: Valor - Data: 02/05/2011</h3>
    <br />
</div>